/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_immortal_fiddler_core_Fiddler */

#ifndef _Included_com_immortal_fiddler_core_Fiddler
#define _Included_com_immortal_fiddler_core_Fiddler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    start0
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_immortal_fiddler_core_Fiddler_start0
	(JNIEnv *, jclass);

	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    close0
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_immortal_fiddler_core_Fiddler_close0
	(JNIEnv *, jclass);

	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    setCallBack0
	* Signature: (Lcom/immortal/fiddler/core/FiddlerCallBack;)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_immortal_fiddler_core_Fiddler_setCallBack0
	(JNIEnv *, jclass, jobject);

	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    createAndTrustRootCert0
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_immortal_fiddler_core_Fiddler_createAndTrustRootCert0
	(JNIEnv *, jclass);

	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    removeCert0
	* Signature: (Z)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_immortal_fiddler_core_Fiddler_removeCert0
	(JNIEnv *, jclass, jboolean);


	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    writeLog0
	* Signature: (ILjava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_com_immortal_fiddler_core_Fiddler_writeLog0
	(JNIEnv *, jclass, jint, jstring);

	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    getFiddlerConfig0
	* Signature: ()Lcom/immortal/fiddler/core/FiddlerConfig;
	*/
	JNIEXPORT jobject JNICALL Java_com_immortal_fiddler_core_Fiddler_getFiddlerConfig0
	(JNIEnv *, jclass);

	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    setFiddlerConfig0
	* Signature: (Lcom/immortal/fiddler/core/FiddlerConfig;)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_immortal_fiddler_core_Fiddler_setFiddlerConfig0
	(JNIEnv *, jclass, jobject);

	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    exportRootCert0
	* Signature: (Ljava/lang/String;)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_immortal_fiddler_core_Fiddler_exportRootCert0
	(JNIEnv *, jclass, jstring);

	/*
	* Class:     com_immortal_fiddler_core_Fiddler
	* Method:    modifyFiddlerData0
	* Signature: (Lcom/immortal/fiddler/core/FiddlerData;)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_immortal_fiddler_core_Fiddler_modifyFiddlerData0
	(JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
